import {regexMapModsCHINESE} from "../generated/mapmods/Generated.MapModsV3.CHINESE";
import {regexMapModsENGLISH} from "../generated/mapmods/Generated.MapModsV3.ENGLISH";
import {Regex} from "../generated/GeneratedTypes";
import {MapModsTokenOption} from "../generated/mapmods/GeneratedTypes";
import {regexMapModsFRENCH} from "../generated/mapmods/Generated.MapModsV3.FRENCH";
import {regexMapModsGERMAN} from "../generated/mapmods/Generated.MapModsV3.GERMAN";
import {regexMapModsJAPANESE} from "../generated/mapmods/Generated.MapModsV3.JAPANESE";
import {regexMapModsKOREAN} from "../generated/mapmods/Generated.MapModsV3.KOREAN";
import {regexMapModsPORTUGUESE} from "../generated/mapmods/Generated.MapModsV3.PORTUGUESE";
import {regexMapModsRUSSIAN} from "../generated/mapmods/Generated.MapModsV3.RUSSIAN";
import {regexMapModsSPANISH} from "../generated/mapmods/Generated.MapModsV3.SPANISH";
import {regexMapModsTHAI} from "../generated/mapmods/Generated.MapModsV3.THAI";

export type RepoeLanguageData = {
  readonly urlKey: string;
  readonly short: string;
  readonly name: string;
  readonly flag: string;
};

export const RepoeLanguage = {
  ENGLISH: {urlKey: "", short: "en", name: "English", flag: "🇺🇸"},
  FRENCH: {urlKey: "French", short: "fr", name: "French", flag: "🇫🇷"},
  GERMAN: {urlKey: "German", short: "de", name: "German", flag: "🇩🇪"},
  JAPANESE: {urlKey: "Japanese", short: "ja", name: "Japanese", flag: "🇯🇵"},
  KOREAN: {urlKey: "Korean", short: "ko", name: "Korean", flag: "🇰🇷"},
  PORTUGUESE: {urlKey: "Portuguese", short: "pt", name: "Portuguese", flag: "🇵🇹"},
  RUSSIAN: {urlKey: "Russian", short: "ru", name: "Russian", flag: "🇷🇺"},
  SPANISH: {urlKey: "Spanish", short: "es", name: "Spanish", flag: "🇪🇸"},
  THAI: {urlKey: "Thai", short: "th", name: "Thai", flag: "🇹🇭"},
  CHINESE: {urlKey: "Traditional%20Chinese", short: "zh", name: "Chinese", flag: "🇨🇳"},
} as const;

export const LanguageFiles: {
  mapmods: Record<RepoeLanguageKey, Regex<MapModsTokenOption>>
} = {
  mapmods: {
    ENGLISH:    regexMapModsENGLISH,
    FRENCH:     regexMapModsFRENCH,
    GERMAN:     regexMapModsGERMAN,
    JAPANESE:   regexMapModsJAPANESE,
    KOREAN:     regexMapModsKOREAN,
    PORTUGUESE: regexMapModsPORTUGUESE,
    RUSSIAN:    regexMapModsRUSSIAN,
    SPANISH:    regexMapModsSPANISH,
    THAI:       regexMapModsTHAI,
    CHINESE:    regexMapModsCHINESE,
  }
};

export type RepoeLanguageKey = keyof typeof RepoeLanguage;

export const MapStaticStatRegex: Record<RepoeLanguageKey, {
  quantity: string,
  packsize: string,
  mapdrop: string,
  itemrarity: string,
  currency: string,
  quality_regular: string,
  quality_currency: string,
  quality_divination: string,
  quality_rarity: string,
  quality_packsize: string,
  quality_scarab: string,
  rarity_prefix: string,
  rarity_normal: string,
  rarity_magic: string,
  rarity_rare: string,
  corrupted: string,
  unidentified: string,
}> = {
  ENGLISH: {
    quantity: "m q.*",
    packsize: "iz.*",
    mapdrop: "re maps.*",
    itemrarity: "m rar.*",
    currency: "cy:.*",
    quality_regular: "ty \\(Quantity\\):.*",
    quality_currency: "\\(Curr.*",
    quality_divination: "div.*",
    quality_rarity: "ty\\).*",
    quality_packsize: "ze\\).*",
    quality_scarab: "sca.*",
    rarity_prefix: "y: ",
    rarity_normal: "n",
    rarity_magic: "m",
    rarity_rare: "r",
    corrupted: "pte",
    unidentified: "tified",
  },
  FRENCH: {
    quantity: "m q.*",
    packsize: "iz.*",
    mapdrop: "re maps.*",
    itemrarity: "m rar.*",
    currency: "cy:.*",
    quality_regular: "ty \\(Quantity\\):.*",
    quality_currency: "\\(Curr.*",
    quality_divination: "div.*",
    quality_rarity: "ty\\).*",
    quality_packsize: "ze\\).*",
    quality_scarab: "sca.*",
    rarity_prefix: "ть: ",
    rarity_normal: "n",
    rarity_magic: "m",
    rarity_rare: "r",
    corrupted: "pte",
    unidentified: "tified",
  },
  GERMAN: {
    quantity: "m q.*",
    packsize: "iz.*",
    mapdrop: "re maps.*",
    itemrarity: "m rar.*",
    currency: "cy:.*",
    quality_regular: "ty \\(Quantity\\):.*",
    quality_currency: "\\(Curr.*",
    quality_divination: "div.*",
    quality_rarity: "ty\\).*",
    quality_packsize: "ze\\).*",
    quality_scarab: "sca.*",
    rarity_prefix: "y: ",
    rarity_normal: "n",
    rarity_magic: "m",
    rarity_rare: "r",
    corrupted: "pte",
    unidentified: "tified",
  },
  JAPANESE: {
    quantity: "m q.*",
    packsize: "iz.*",
    mapdrop: "re maps.*",
    itemrarity: "m rar.*",
    currency: "cy:.*",
    quality_regular: "ty \\(Quantity\\):.*",
    quality_currency: "\\(Curr.*",
    quality_divination: "div.*",
    quality_rarity: "ty\\).*",
    quality_packsize: "ze\\).*",
    quality_scarab: "sca.*",
    rarity_prefix: "y: ",
    rarity_normal: "n",
    rarity_magic: "m",
    rarity_rare: "r",
    corrupted: "pte",
    unidentified: "tified",
  },
  KOREAN: {
    quantity: "m q.*",
    packsize: "iz.*",
    mapdrop: "re maps.*",
    itemrarity: "m rar.*",
    currency: "cy:.*",
    quality_regular: "ty \\(Quantity\\):.*",
    quality_currency: "\\(Curr.*",
    quality_divination: "div.*",
    quality_rarity: "ty\\).*",
    quality_packsize: "ze\\).*",
    quality_scarab: "sca.*",
    rarity_prefix: "y: ",
    rarity_normal: "n",
    rarity_magic: "m",
    rarity_rare: "r",
    corrupted: "pte",
    unidentified: "tified",
  },
  PORTUGUESE: {
    quantity: "m q.*",
    packsize: "iz.*",
    mapdrop: "re maps.*",
    itemrarity: "m rar.*",
    currency: "cy:.*",
    quality_regular: "ty \\(Quantity\\):.*",
    quality_currency: "\\(Curr.*",
    quality_divination: "div.*",
    quality_rarity: "ty\\).*",
    quality_packsize: "ze\\).*",
    quality_scarab: "sca.*",
    rarity_prefix: "y: ",
    rarity_normal: "n",
    rarity_magic: "m",
    rarity_rare: "r",
    corrupted: "pte",
    unidentified: "tified",
  },
  RUSSIAN: {
    quantity: "Количество.*",
    packsize: "монстров.*",
    mapdrop: "ьше карт.*",
    itemrarity: "Редкость.*",
    currency: "юты:.*",
    quality_regular: "во:.*",
    quality_currency: "люта\\)*",
    quality_divination: "гадальных.*",
    quality_rarity: "сть\\).*",
    quality_packsize: "ппы\\).*",
    quality_scarab: "беи\\).*",
    rarity_prefix: "y: ",
    rarity_normal: "о",
    rarity_magic: "в",
    rarity_rare: "р",
    corrupted: "оскв",
    unidentified: "неоп",
  },
  SPANISH: {
    quantity: "m q.*",
    packsize: "iz.*",
    mapdrop: "re maps.*",
    itemrarity: "m rar.*",
    currency: "cy:.*",
    quality_regular: "ty \\(Quantity\\):.*",
    quality_currency: "\\(Curr.*",
    quality_divination: "div.*",
    quality_rarity: "ty\\).*",
    quality_packsize: "ze\\).*",
    quality_scarab: "sca.*",
    rarity_prefix: "y: ",
    rarity_normal: "n",
    rarity_magic: "m",
    rarity_rare: "r",
    corrupted: "pte",
    unidentified: "tified",
  },
  THAI: {
    quantity: "m q.*",
    packsize: "iz.*",
    mapdrop: "re maps.*",
    itemrarity: "m rar.*",
    currency: "cy:.*",
    quality_regular: "ty \\(Quantity\\):.*",
    quality_currency: "\\(Curr.*",
    quality_divination: "div.*",
    quality_rarity: "ty\\).*",
    quality_packsize: "ze\\).*",
    quality_scarab: "sca.*",
    rarity_prefix: "y: ",
    rarity_normal: "n",
    rarity_magic: "m",
    rarity_rare: "r",
    corrupted: "pte",
    unidentified: "tified",
  },
  CHINESE: {
    quantity: "^物品數量.*",
    packsize: "^怪物群大小.*",
    mapdrop: "^更多地圖.*",
    itemrarity: "^物品稀有度.*",
    currency: "通貨:.*",
    quality_regular: "^品質.*物品數量.*",
    quality_currency: "^品質.*通貨.*",
    quality_divination: "^品質.*命運卡.*",
    quality_rarity: "^品質.*稀有度.*",
    quality_packsize: "^品質.*怪物群大小.*",
    quality_scarab: "^品質.*聖甲蟲.*",
    rarity_prefix: "^稀有度: ",
    rarity_normal: "普通",
    rarity_magic: "魔法",
    rarity_rare: "稀有",
    corrupted: "^已汙染$",
    unidentified: "^未鑑定$",
  },
};